added vpc data
LeanerCloud/ec2-instances-info pull request #28
Opened 2023-01-31 15:42 UTC by yariv-doit

removed comments from VPC info

why was this comment out? 
I find these fields useful  
can it be merged to main repository?

2023-02-01 14:12 UTC, cristim requested changes
Awesome, I honestly never needed those fields before. There are probably dozens of other fields available in the JSON that we don't expose yet.

There's also a concern on possible memory consumption at runtime if we expose more data, we may need to make it configurable.

2023-02-01 14:12 UTC, cristim commented on examples/instances/instances.go
> +	ec2instancesinfo "github.com/yariv-doit/ec2-instances-info"
Please keep this out of the commit.

2023-02-01 14:12 UTC, cristim commented on go.mod
> -	github.com/pkg/errors v0.9.1
And this

2023-02-01 14:12 UTC, cristim commented on go.sum
> -github.com/go-bindata/go-bindata v3.1.2+incompatible/go.mod h1:xK8Dsgwmeed+BBsSy2XTopBn/8uK2HWuGSnA11C3Joo=
Not sure why this is still shown, we no longer use go-bindata.

2023-02-01 17:13 UTC, yariv-doit commented on go.mod
> -	github.com/pkg/errors v0.9.1
not sure I understand, this was removed by `go mod tidy`
you state below "we're not using go-bindata"

2023-02-01 17:20 UTC, yariv-doit commented
looks like the test are failing due to go version 
https://github.com/terraform-docs/terraform-docs/issues/474
... [Embedded Files](https://tip.golang.org/doc/go1.16#library-embed) was added in go1.16.

2023-02-01 17:31 UTC, yariv-doit commented on examples/instances/instances.go
> +	ec2instancesinfo "github.com/yariv-doit/ec2-instances-info"
sorry, published locally, didn't notice it came into the PR, fixed

2023-02-07 09:10 UTC, yariv-doit commented
Hi @cristim
first of all, I did not have a chance to thank you for your package
I'm updating the PR description for the reason for this change request

2023-02-07 09:35 UTC, cristim commented
Thanks for the contribution @yariv-doit, glad you find this useful.

Unfortunately I'm really busy with other higher priority work so don't have time to look into this over the next few days but I'll check it out next week.

2023-02-14 10:01 UTC, cristim commented
@yariv-doit I updated the Github Action to use newer versions of Go, please rebase this PR to make use of that.

2023-02-14 10:04 UTC, cristim commented on go.sum
> -github.com/go-bindata/go-bindata v3.1.2+incompatible/go.mod h1:xK8Dsgwmeed+BBsSy2XTopBn/8uK2HWuGSnA11C3Joo=
I did a commit that just did `go mod tidy`so this should no longer be needed.

2023-02-20 15:10 UTC, closed without merging

2023-02-25 20:42 UTC, cristim commented
oh, i messed up, didn't intend to close this, sorry @yariv-doit.

I was just trying to use this https://docs.github.com/en/repositories/working-with-files/managing-large-files/configuring-git-large-file-storage in order to decrease the size of the repo but the Go tooling breaks with it.

Please rebase your changes against the current HEAD and make another PR.

Sorry for the inconvenience.